# -*- coding: utf-8 -*-
"""4212111038_Serly R.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l67NVZnu1Ggq2LIr9SJCC_IGr4TpdH84
"""
#digunakan untuk menginstal tiga paket Python yang berbeda
pip install scikit-learn numpy scikit-image

#Import library yang digunakan
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from skimage.feature import hog
from skimage import exposure

# Kode untuk memuat dataset MNIST menggunakan modul datasets dari scikit-learn 
digits = datasets.load_digits()

# Kode ini mendefinisikan fungsi ekstrak_hog_features yang melakukan 
# ekstraksi fitur Histogram of Oriented Gradients (HOG) pada kumpulan gambar
def extract_hog_features(images):
    features = []
    for image in images:
        fd, hog_image = hog(image.reshape((8, 8)), orientations=8, pixels_per_cell=(2, 2), cells_per_block=(1, 1), visualize=True)
        features.append(fd)
    return np.array(features)

# untuk split/membagi dataset menjadi 2 bagian utama, test & train
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=42)

# Kode ini melakukan ekstraksi fitur
# menggunakan metode Histogram of Oriented Gradients (HOG).
X_train_hog = extract_hog_features(X_train)
X_test_hog = extract_hog_features(X_test)

# Kode ini berhubungan dengan standardisasi fitur (feature scaling), 
scaler = StandardScaler().fit(X_train_hog)
X_train_hog = scaler.transform(X_train_hog)
X_test_hog = scaler.transform(X_test_hog)

# Melatih model SVM dengan data pelatihan.
svm_model = SVC(kernel='linear', C=1)
svm_model.fit(X_train_hog, y_train)
# Memprediksi label untuk data uji menggunakan model yang telah dilatih.
y_pred = svm_model.predict(X_test_hog)

# kode ini untuk evaluasi kinerja model klasifikasi pada suatu dataset
#Mengukur akurasi model
accuracy = accuracy_score(y_test, y_pred)
#Mengukur presisi model
precision = precision_score(y_test, y_pred, average='weighted')
#Membuat confusion matriks
conf_matrix = confusion_matrix(y_test, y_pred)

# Menampilkan nilai akurasi, presisi serta confusion matrix
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Confusion Matrix:\n", conf_matrix)